name: Compile and build FW

# Trigger the workflow on push or pull request on any branch
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      # Install common reqired packages: gcc, avr-libc, avrdude, python3, python3-pip
      run: sudo apt-get install -y gcc-avr binutils-avr avr-libc avrdude python3 python3-pip zip
    - name: Compile firmware
      run: ./fbt updater_package
    - name: Upload dev artifact
      uses: actions/upload-artifact@v2
      with:
        name: update.tgz
        path: dist/*/*.tgz
